<?php

use CodeIgniter\Router\RouteCollection;

/**
 * @var RouteCollection $routes
 */
//pages
$routes->get('/', 'Home::index');
$routes->get('view-matches','Home::viewMatches');
$routes->get('latest-news','Home::latestNews');
$routes->get('latest-news/stories/(:any)','Home::stories/$1');
$routes->get('watch-now','Home::watchNow');
$routes->get('/chat/getMessages', 'ChatController::getMessages');
$routes->post('/chat/sendMessage', 'ChatController::sendMessage');
$routes->get('watch/(:any)','Home::watch/$1');
$routes->post('incrementViews/(:num)', 'Home::incrementViews/$1');
$routes->post('save_watch_time','Home::saveWatchTime');
$routes->get('latest-events','Home::latestEvents');
$routes->get('latest-events/details/(:any)','Home::eventDetails/$1');
$routes->get('shop-near-me','Home::shopNearMe');
$routes->get('contact-us','Home::contactUs');
//functions for user 
$routes->post('register-now','User::registerNow');
$routes->post('new-password','User::newPassword');
//authentication
$routes->post('check','Home::checkAccount');
$routes->get('logout','Home::logout');
$routes->post('request-new-password','Home::requestNewPassword');
$routes->post('change-password','Home::changePassword');
//fan
$routes->post('validate','User::validateUser');
$routes->post('register','User::register');
$routes->get('sign-out','User::signout');
// ajax request
///user management
$routes->get('fetch-accounts','Home::fetchAccounts');
$routes->post('save-account','Home::saveAccount');
$routes->post('update','Home::updateAccount');
$routes->post('reset','Home::resetAccount');
///settings
$routes->get('fetch-sports','Home::fetchSports');
$routes->post('save-sports','Home::saveSports');
$routes->post('save-role','Home::saveRole');
$routes->get('fetch-role','Home::fetchRole');
$routes->get('fetch-achievement','Home::fetchAchievement');
$routes->post('save-achievement','Home::saveAchievement');
//team
$routes->post('save-team','Home::saveTeam');
$routes->get('filter-team','Home::filterTeam');
//player
$routes->post('save-player','Home::savePlayer');
$routes->get('get-position','Home::getPosition');
$routes->get('filter-players','Home::filterPlayers');
$routes->get('search-players','Coach::searchPlayers');
$routes->post('edit-player','Home::editPlayer');
//map
$routes->get('shop-location','Home::shopLocation');
$routes->post('save-shop','Home::saveShop');
$routes->get('fetch-shop','Home::fetchShop');
$routes->post('edit-shop','Home::editShop');
//events
$routes->post('save-event','Home::saveEvent');
$routes->post('cancel-event','Home::cancelEvent');
$routes->get('fetch-event','Home::fetchEvent');
$routes->post('accept-event','Home::acceptEvent');
$routes->post('reject-event','Home::rejectEvent');
$routes->post('add-remarks','Home::addRemarks');
//news
$routes->post('save-post','Home::savePost');
$routes->post('modify-post','Home::modifyPost');
$routes->post('save-as-draft','Home::saveDraft');
$routes->get('filter-news','Home::filterNews');
//video
$routes->post('save-video','Home::saveVideo');
$routes->post('edit-video','Home::modifyVideo');
$routes->get('filter-videos','Home::filterVideos');
//live
$routes->post('save-code','Home::saveCode');
//matches
$routes->post('save-match','Home::saveMatch');
$routes->post('stats','Home::stats');
$routes->post('add-score-team-1','Home::addScore1');
$routes->post('minus-score-team-1','Home::minusScore1');
$routes->post('add-score-team-2','Home::addScore2');
$routes->post('minus-score-team-2','Home::minusScore2');
$routes->get('team1-score','Home::teamHome');
$routes->get('team2-score','Home::teamGuest');
$routes->post('end-game','Home::endGame');
//recovery
$routes->post('restore','Restore::restoreFile');
$routes->get('download','Download::downloadFile');
//ads
$routes->post('save-ads','Home::saveAds');
$routes->get('fetch-data','Home::fetchAds');
$routes->post('edit-ads','Home::editAds');

$routes->group('',['filter'=>'UserAlreadyLoggedIn'],function($routes)
{
    $routes->get('login','User::login');
    $routes->get('reset-password','User::resetPassword');
    $routes->get('sign-up','User::signUp');
    $routes->get('success/(:any)','Home::successLink/$1');
    $routes->get('resend/(:any)','Home::resend/$1');
    $routes->get('activate/(:any)','Home::activateAccount/$1');
});

$routes->group('',['filter'=>'AlreadyLoggedIn'],function($routes)
{
    $routes->get('auth','Home::auth');
    $routes->get('forgot-password','Home::forgotPassword');
});

$routes->group('',['filter'=>'AuthCheck'],function($routes)
{
    $routes->get('dashboard','Home::dashboard');
    //players
    $routes->get('athletes','Home::fetchAthletes');
    $routes->get('new-athlete','Home::newAthlete');
    $routes->get('athletes/profile/(:any)','Home::playerProfile/$1');
    $routes->get('athletes/edit-profile/(:any)','Home::editProfile/$1');
    //teams
    $routes->get('teams','Home::fetchTeams');
    $routes->get('teams/details/(:any)','Home::teamDetails/$1');
    $routes->get('teams/score/(:any)','Home::teamResults/$1');
    $routes->get('new-team','Home::newTeam');
    //accounts
    $routes->get('accounts','Home::accounts');
    $routes->get('new-account','home::newAccount');
    $routes->get('edit-account/(:any)','home::editAccount/$1');
    //events
    $routes->get('events','Home::Events');
    $routes->get('new-event','Home::newEvent');
    $routes->get('manage-event','Home::manageEvent');
    //shops
    $routes->get('shops','Home::shops');
    //matches
    $routes->get('new-match','Home::newMatch');
    $routes->get('matches','Home::allMatch');
    $routes->get('match-details/(:any)','Home::scoreMatch/$1');
    //videos
    $routes->get('videos','Home::manageVideos');
    $routes->get('upload-video','Home::uploadVideo');
    $routes->get('go-live','Home::goLive');
    $routes->get('videos/play/(:any)','Home::playVideo/$1');
    $routes->get('videos/edit/(:any)','Home::editVideo/$1');
    //news
    $routes->get('news','Home::news');
    $routes->get('news/topic/(:any)','Home::topic/$1');
    $routes->get('new-article','Home::newPost');
    $routes->get('news/edit/(:any)','Home::editPost/$1');
    //sponsors
    $routes->get('sponsors','Home::sponsors');
    //settings
    $routes->get('settings','Home::settings');
    $routes->get('recovery','Home::recovery');
    //accounts
    $routes->get('my-account','Home::myAccount');
    //coach
    $routes->get('overview','Coach::dashboard');
    $routes->get('my-players','Coach::myPlayers');
    $routes->get('view/(:any)','Coach::viewPlayer/$1');
    $routes->get('new-player','Coach::newPlayer');
    $routes->get('my-team','Coach::myTeam');
    $routes->get('my-schedule','Coach::mySchedule');
    $routes->get('my-profile','Coach::myAccount');
    $routes->get('latest-events/register/(:any)','Home::eventRegistration/$1');
    $routes->get('results','Coach::gameResults');
});